/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import Utilidades.Automata;
import javax.swing.JOptionPane;

/**
 *
 * @author branp
 */
public class ISeleccion extends javax.swing.JDialog {

    /**
     * Creates new form ISeleccion
     */
    private Automata Estados;
    private IG1 MenuInicial; 
    private String Contenido;
    private ITokens MenuTokens;
    private IErrores MenuErrores;
    public ISeleccion(Automata Guardado, String Cont) {
        initComponents();
        Contenido = Cont;
        Estados = Guardado;
        Estados.Analizar(AreaDeEstados);
        AreaDeEstados.setEnabled(false);
        if (Estados.TieneErrores()) {
            BotonErrores.setEnabled(true);
        }else{
            BotonTokens.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BotonErrores = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaDeEstados = new javax.swing.JTextArea();
        BotonTokens = new javax.swing.JButton();
        BotonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Seleccione una opción:");

        BotonErrores.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BotonErrores.setText("Ver errores");
        BotonErrores.setEnabled(false);
        BotonErrores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonErroresActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Movimiento de estados:");

        AreaDeEstados.setColumns(20);
        AreaDeEstados.setRows(5);
        AreaDeEstados.setFocusable(false);
        jScrollPane1.setViewportView(AreaDeEstados);

        BotonTokens.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BotonTokens.setText("Mostrar Tokens");
        BotonTokens.setEnabled(false);
        BotonTokens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTokensActionPerformed(evt);
            }
        });

        BotonRegresar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BotonRegresar.setText("Regresar al texto");
        BotonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BotonErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(BotonTokens)
                        .addGap(29, 29, 29)
                        .addComponent(BotonRegresar))
                    .addComponent(jLabel2))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonErrores)
                    .addComponent(BotonTokens)
                    .addComponent(BotonRegresar))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonErroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonErroresActionPerformed
        MenuErrores = new IErrores(Estados, Contenido);
        MenuErrores.setVisible(true);
        MenuErrores.setLocationRelativeTo(null);
        MenuErrores.setTitle("Menu Error");
        this.dispose();
    }//GEN-LAST:event_BotonErroresActionPerformed

    private void BotonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarActionPerformed
        // TODO add your handling code here:
        MenuInicial = new IG1(Contenido);
        MenuInicial.setVisible(true);
        MenuInicial.setLocationRelativeTo(null);
        MenuInicial.setTitle("Menu Principal");
        this.dispose();
    }//GEN-LAST:event_BotonRegresarActionPerformed

    private void BotonTokensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTokensActionPerformed
        // TODO add your handling code here:
        MenuTokens = new ITokens(Estados, Contenido);
        MenuTokens.setVisible(true);
        MenuTokens.setLocationRelativeTo(null);
        MenuTokens.setTitle("Menu tokens");
        this.dispose();
    }//GEN-LAST:event_BotonTokensActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaDeEstados;
    private javax.swing.JButton BotonErrores;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JButton BotonTokens;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
